version: '2.4'
services:
    todoapp-dev:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
            
        ports:
            - "5100:5100"
        
        env_file:
            - .env

        volumes:
            - ./todo_app:/code/todo_app
